package com.mohammadramadan.android.findyourmovie;

import android.app.Activity;
import android.os.Bundle;
import android.widget.ListView;

import java.util.ArrayList;

public class RomanticActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.list_view);

    final ArrayList<Items> item = new ArrayList<Items>();

    item.add(new Items("The Notebook","7.9 / 10", "In a nursing home, resident Duke reads a romance story to an old woman who has senile dementia with memory loss. In the late 1930s, wealthy seventeen year-old Allie Hamilton is spending summer vacation in Seabrook. Local worker Noah Calhoun meets Allie at a carnival and they soon fall in love with each other. One day, Noah brings Allie to an ancient house that he dreams of buying and restoring and they attempt to make love but get interrupted by their friend. Allie's parents do not approve of their romance since Noah belongs to another social class, and they move to New York with her. Noah writes 365 letters (A Year) to Allie, but her mother Anne Hamilton does not deliver them to her daughter. Three years later, the United States joins the World War II and Noah and his best friend Fin enlist in the army, and Allie works as an army nurse. She meets injured soldier Lon Hammond in the hospital. After the war, they meet each other again going on dates and then, Lon, who is wealthy and ... Written by Claudio Carvalho, Rio de Janeiro, Brazil",R.drawable.the_notebook));
    item.add(new Items("Silver Linings Playbook","7.7 / 10","Against medical advice and without the knowledge of her husband Pat Solatano Sr., caring Dolores Solatano discharges her adult son, Pat Solatano Jr., from a Maryland mental health institution after his minimum eight month court ordered stint. The condition of the release includes Pat Jr. moving back in with his parents in their Philadelphia home. Although Pat Jr.'s institutionalization was due to him beating up the lover of his wife Nikki, he was diagnosed with bipolar disorder. Nikki has since left him and has received a restraining order against him. Although he is on medication (which he doesn't take because of the way it makes him feel) and has mandatory therapy sessions, Pat Jr. feels like he can manage on the outside solely by healthy living and looking for the \"silver linings\" in his life. His goals are to get his old job back as a substitute teacher, but more importantly reunite with Nikki. He finds there are certain instances where he doesn't cope well, however no less so ... Written by Huggo",R.drawable.silver_linings_playbook));
    item.add(new Items("My Sassy Girl","6.3 / 10","My Sassy Girl is the tale of the first and last time Charlie Bello falls in love. From their initial meeting, trouble is the name of the game. Imagine an amorphous mass of dating disasters and you get an idea of the relationship between the young couple. Some mysterious force with the strength of gravity between two planets must be at play between Charlie and Jordan as the relationship truly makes no sense on the surface. Everything seems pitted against the two of them. Things suddenly come to a halt when the two write letters confessing their love for each other. Agreeing to meet a year later to read the love letters together, Charlie and Jordan go their separate ways. Written by Marx-Michael",R.drawable.my_sassy_girl));
    item.add(new Items("Dirty Dancing","6.9 / 10", "In 1963, Frances \"Baby\" Houseman, a sweet daddy's girl, goes with her family to a resort in upstate New York's Catskill Mountains. Baby has grown up in privileged surroundings and all expect her to go on to college, join the Peace Corps and save the world before marrying a doctor, just like her father. Unexpectedly, Baby becomes infatuated with the camp's dance instructor, Johnny Castle, a man whose background is vastly different from her own. Baby lies to her father to get money to pay for an illegal abortion for Johnny's dance partner. She then fills in as Johnny's dance partner and it is as he is teaching her the dance routine that they fall in love. It all comes apart when Johnny's friend falls seriously ill after her abortion and Baby gets her father, who saves the girl's life. He then learns what Baby has been up to, who with and worse, that he funded the illegal abortion. He bans his daughter from any further association with \"those people\". In the first deliberately willful ... Written by Amanda W, amended by Linda C.",R.drawable.dirty_dancing));
    item.add(new Items("A Walk To Remember","7.4 / 10", "In North Carolina especially in Beaufort a prank on a guy goes wrong and puts the student in the clinic. Carter, a famous student with no plans for the future, is held responsible and forced to join in after-school community service activities as consequence, which include starring as the lead in the play. And participating in these activities is Jamie Sullivan, the reverend's daughter who has great ambitions and nothing in common with Landon. When Landon decides he wants to take his activities seriously, he asks Jamie for help and begins to spend most of his time with her. But he starts to like her, that he did not expect to do. They relationship, much to the chagrin of Landon's old popular friends and Jamie's strict reverend father. But when a heart-breaking secret becomes known that puts their relationship to the test, it is then that Landon and Jamie realize the true meaning of love and fate. Written by Pjshipman",R.drawable.walk_to_remember));
    item.add(new Items("If Only","7.2 / 10", "After his impetuous musician girlfriend, Samantha, dies in an accident shortly after they had a fight (and nearly broke up), a grief-stricken British businessman, Ian Wyndham, living in London gets a chance to relive the day all over again, in the hope of changing the events that led up to her getting killed. Written by austin4577@aol.com",R.drawable.if_only));
    item.add(new Items("Love Rose - Für immer vielleicht","7.2 / 10", "From the age of 5 Rosie Dunne and Alex Stewart have been best friends, as they take on life they just end up getting separated time and time again. When it comes to love it's just everyone else but each other... But when will they realise they are meant to be together?",R.drawable.love_rosie));

    ItemsAdapter adapter =new ItemsAdapter(this, item);
        ListView listView = (ListView) findViewById(R.id.list);
        listView.setAdapter(adapter);
    }

}

